image: alpine:latest

pages:
  stage: deploy
  script:
    - rm public -rf
    - mkdir public
    - cp -r src/* public
    - cp -r lib public/
    - cp -r static public/
  artifacts:
    paths:
    - public
  only:
  - master
